# Generated by Django 4.2.8 on 2024-01-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
